# Generated by Django 4.1.1 on 2022-09-24 02:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OrederPlaced",
            new_name="OrderPlaced",
        ),
    ]
